### ISSUE TITLE
Last changed after restart ?

### ISSUE THREAD

**Issue by camui-alexandru** [queimadus/last-changed-element#4]
After I restart HA, the door sensors shows the restart time. How can I resolve this ? I searched alot on google but i dont understand how can I do that.

**Comment by queimadus** [comment]
This is a current limitation of Home Assistant. The `last_changed` gets updated when there is a restart. 
There is a feature request to change this behavior you can track if you'd like to follow its progress: https://community.home-assistant.io/t/retain-last-state-change-data-of-a-sensor-after-reboot/125148
